global: 
 message: welcome to oder service dev environment!!
server:
 port: 8082
message: hello from  Oder dev!!
spring:
  datasource:
    url: jdbc:mysql://localhost:3036/oder_dev
    username: root
    pasword: 
jpa: 
  hibernate:
   ddl-auto: none
   show-sql: true
