global: 
 message: welcome to Oder service prod environment!!
server:
 port: 8082
message: hello from  Oder prod!!
spring:
  datasource:
    url: jdbc:mysql://localhost:3036/oder_dev
    username: root
    pasword: 
jpa: 
  hibernate:
   ddl-auto: update
   show-sql: true
